packages:
  - pkg/js/rest
  - pkg/js/test/rest

autoInstallPeers: true

gitChecks: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - protobufjs

overrides:
  "@sveltejs/kit@>=2.19.0 <=2.49.4": ">=2.49.5"
  "@sveltejs/kit@>=2.49.0 <=2.49.4": ">=2.49.5"
  "@sveltejs/kit@>=2.49.0 <=2.52.1": ">=2.52.2"
  brace-expansion@<5.0.5: ">=5.0.5"
  cookie@<0.7.0: ">=0.7.0"
  fast-xml-parser@>=4.0.0-beta.3 <=5.5.6: ">=5.5.7"
  flatted@<=3.4.1: ">=3.4.2"
  handlebars@>=4.0.0 <4.7.9: ">=4.7.9"
  lodash-es@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@>=10.0.0 <10.2.3: ">=10.2.3"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  storybook@>=10.0.0 <10.1.10: ">=10.1.10"
  storybook@>=10.0.0-beta.0 <10.2.10: ">=10.2.10"
  svelte@<=5.51.4: ">=5.51.5"
  svelte@<=5.53.4: ">=5.53.5"
  svelte@>=5.39.3 <5.51.5: ">=5.51.5"
  undici@<6.24.0: ">=6.24.0"
  undici@>=6.0.0 <6.24.0: ">=6.24.0"
  undici@>=7.0.0 <7.24.0: ">=7.24.0"
  undici@>=7.17.0 <7.24.0: ">=7.24.0"

prefer-workspace-packages: true

recursive-install: true

strictPeerDependencies: false
