packages:
  - pkg/js/rest
  - pkg/js/test/rest

autoInstallPeers: true

gitChecks: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - protobufjs

prefer-workspace-packages: true

recursive-install: true

strictPeerDependencies: false

overrides:
  "@sveltejs/kit@>=2.19.0 <=2.49.4": ">=2.49.5"
  "@sveltejs/kit@>=2.49.0 <=2.49.4": ">=2.49.5"
  "@sveltejs/kit@>=2.49.0 <=2.52.1": ">=2.52.2"
  cookie@<0.7.0: ">=0.7.0"
  lodash-es@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@>=10.0.0 <10.2.3: ">=10.2.3"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  storybook@>=10.0.0 <10.1.10: ">=10.1.10"
  storybook@>=10.0.0-beta.0 <10.2.10: ">=10.2.10"
  svelte@<=5.51.4: ">=5.51.5"
  svelte@<=5.53.4: ">=5.53.5"
  svelte@>=5.39.3 <5.51.5: ">=5.51.5"
