// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-template/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreateDao creates a new instance of MockItemCreateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateDao {
	mock := &MockItemCreateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateDao is an autogenerated mock type for the ItemCreateDao type
type MockItemCreateDao struct {
	mock.Mock
}

type MockItemCreateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateDao) EXPECT() *MockItemCreateDao_Expecter {
	return &MockItemCreateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateDao
func (_mock *MockItemCreateDao) Exec(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemCreateRequest
func (_e *MockItemCreateDao_Expecter) Exec(ctx any, request any) *MockItemCreateDao_Exec_Call {
	return &MockItemCreateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemCreateRequest)) *MockItemCreateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error)) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteDao creates a new instance of MockItemDeleteDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteDao {
	mock := &MockItemDeleteDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteDao is an autogenerated mock type for the ItemDeleteDao type
type MockItemDeleteDao struct {
	mock.Mock
}

type MockItemDeleteDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteDao) EXPECT() *MockItemDeleteDao_Expecter {
	return &MockItemDeleteDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteDao
func (_mock *MockItemDeleteDao) Exec(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemDeleteRequest
func (_e *MockItemDeleteDao_Expecter) Exec(ctx any, request any) *MockItemDeleteDao_Exec_Call {
	return &MockItemDeleteDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemDeleteRequest)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) Return(item *dao.Item, err error) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetDao creates a new instance of MockItemGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetDao {
	mock := &MockItemGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetDao is an autogenerated mock type for the ItemGetDao type
type MockItemGetDao struct {
	mock.Mock
}

type MockItemGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetDao) EXPECT() *MockItemGetDao_Expecter {
	return &MockItemGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetDao
func (_mock *MockItemGetDao) Exec(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemGetRequest
func (_e *MockItemGetDao_Expecter) Exec(ctx any, request any) *MockItemGetDao_Exec_Call {
	return &MockItemGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemGetRequest)) *MockItemGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetDao_Exec_Call) Return(item *dao.Item, err error) *MockItemGetDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error)) *MockItemGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListDao creates a new instance of MockItemListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListDao {
	mock := &MockItemListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListDao is an autogenerated mock type for the ItemListDao type
type MockItemListDao struct {
	mock.Mock
}

type MockItemListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListDao) EXPECT() *MockItemListDao_Expecter {
	return &MockItemListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListDao
func (_mock *MockItemListDao) Exec(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) ([]*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) []*dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemListRequest
func (_e *MockItemListDao_Expecter) Exec(ctx any, request any) *MockItemListDao_Exec_Call {
	return &MockItemListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemListRequest)) *MockItemListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListDao_Exec_Call) Return(items []*dao.Item, err error) *MockItemListDao_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error)) *MockItemListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateDao creates a new instance of MockItemUpdateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateDao {
	mock := &MockItemUpdateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateDao is an autogenerated mock type for the ItemUpdateDao type
type MockItemUpdateDao struct {
	mock.Mock
}

type MockItemUpdateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateDao) EXPECT() *MockItemUpdateDao_Expecter {
	return &MockItemUpdateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateDao
func (_mock *MockItemUpdateDao) Exec(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemUpdateRequest
func (_e *MockItemUpdateDao_Expecter) Exec(ctx any, request any) *MockItemUpdateDao_Exec_Call {
	return &MockItemUpdateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemUpdateRequest)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
