// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: item_get.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemGetService_ItemGet_FullMethodName = "/ItemGetService/ItemGet"
)

// ItemGetServiceClient is the client API for ItemGetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemGetService retrieves an item by ID.
type ItemGetServiceClient interface {
	ItemGet(ctx context.Context, in *ItemGetRequest, opts ...grpc.CallOption) (*ItemGetResponse, error)
}

type itemGetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemGetServiceClient(cc grpc.ClientConnInterface) ItemGetServiceClient {
	return &itemGetServiceClient{cc}
}

func (c *itemGetServiceClient) ItemGet(ctx context.Context, in *ItemGetRequest, opts ...grpc.CallOption) (*ItemGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemGetResponse)
	err := c.cc.Invoke(ctx, ItemGetService_ItemGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemGetServiceServer is the server API for ItemGetService service.
// All implementations must embed UnimplementedItemGetServiceServer
// for forward compatibility.
//
// ItemGetService retrieves an item by ID.
type ItemGetServiceServer interface {
	ItemGet(context.Context, *ItemGetRequest) (*ItemGetResponse, error)
	mustEmbedUnimplementedItemGetServiceServer()
}

// UnimplementedItemGetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemGetServiceServer struct{}

func (UnimplementedItemGetServiceServer) ItemGet(context.Context, *ItemGetRequest) (*ItemGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ItemGet not implemented")
}
func (UnimplementedItemGetServiceServer) mustEmbedUnimplementedItemGetServiceServer() {}
func (UnimplementedItemGetServiceServer) testEmbeddedByValue()                        {}

// UnsafeItemGetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemGetServiceServer will
// result in compilation errors.
type UnsafeItemGetServiceServer interface {
	mustEmbedUnimplementedItemGetServiceServer()
}

func RegisterItemGetServiceServer(s grpc.ServiceRegistrar, srv ItemGetServiceServer) {
	// If the following call panics, it indicates UnimplementedItemGetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemGetService_ServiceDesc, srv)
}

func _ItemGetService_ItemGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemGetServiceServer).ItemGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemGetService_ItemGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemGetServiceServer).ItemGet(ctx, req.(*ItemGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemGetService_ServiceDesc is the grpc.ServiceDesc for ItemGetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemGetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ItemGetService",
	HandlerType: (*ItemGetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ItemGet",
			Handler:    _ItemGetService_ItemGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_get.proto",
}
