// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: item_get.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemGetRequest) Reset() {
	*x = ItemGetRequest{}
	mi := &file_item_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGetRequest) ProtoMessage() {}

func (x *ItemGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGetRequest.ProtoReflect.Descriptor instead.
func (*ItemGetRequest) Descriptor() ([]byte, []int) {
	return file_item_get_proto_rawDescGZIP(), []int{0}
}

func (x *ItemGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ItemGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemGetResponse) Reset() {
	*x = ItemGetResponse{}
	mi := &file_item_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGetResponse) ProtoMessage() {}

func (x *ItemGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGetResponse.ProtoReflect.Descriptor instead.
func (*ItemGetResponse) Descriptor() ([]byte, []int) {
	return file_item_get_proto_rawDescGZIP(), []int{1}
}

func (x *ItemGetResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_item_get_proto protoreflect.FileDescriptor

const file_item_get_proto_rawDesc = "" +
	"\n" +
	"\x0eitem_get.proto\x1a\n" +
	"item.proto\" \n" +
	"\x0eItemGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0fItemGetResponse\x12\x19\n" +
	"\x04item\x18\x01 \x01(\v2\x05.ItemR\x04item2>\n" +
	"\x0eItemGetService\x12,\n" +
	"\aItemGet\x12\x0f.ItemGetRequest\x1a\x10.ItemGetResponseBYB\fItemGetProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_item_get_proto_rawDescOnce sync.Once
	file_item_get_proto_rawDescData []byte
)

func file_item_get_proto_rawDescGZIP() []byte {
	file_item_get_proto_rawDescOnce.Do(func() {
		file_item_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_get_proto_rawDesc), len(file_item_get_proto_rawDesc)))
	})
	return file_item_get_proto_rawDescData
}

var file_item_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_get_proto_goTypes = []any{
	(*ItemGetRequest)(nil),  // 0: ItemGetRequest
	(*ItemGetResponse)(nil), // 1: ItemGetResponse
	(*Item)(nil),            // 2: Item
}
var file_item_get_proto_depIdxs = []int32{
	2, // 0: ItemGetResponse.item:type_name -> Item
	0, // 1: ItemGetService.ItemGet:input_type -> ItemGetRequest
	1, // 2: ItemGetService.ItemGet:output_type -> ItemGetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_get_proto_init() }
func file_item_get_proto_init() {
	if File_item_get_proto != nil {
		return
	}
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_get_proto_rawDesc), len(file_item_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_get_proto_goTypes,
		DependencyIndexes: file_item_get_proto_depIdxs,
		MessageInfos:      file_item_get_proto_msgTypes,
	}.Build()
	File_item_get_proto = out.File
	file_item_get_proto_goTypes = nil
	file_item_get_proto_depIdxs = nil
}
