// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: item_update.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUpdateRequest) Reset() {
	*x = ItemUpdateRequest{}
	mi := &file_item_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUpdateRequest) ProtoMessage() {}

func (x *ItemUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUpdateRequest.ProtoReflect.Descriptor instead.
func (*ItemUpdateRequest) Descriptor() ([]byte, []int) {
	return file_item_update_proto_rawDescGZIP(), []int{0}
}

func (x *ItemUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ItemUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUpdateResponse) Reset() {
	*x = ItemUpdateResponse{}
	mi := &file_item_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUpdateResponse) ProtoMessage() {}

func (x *ItemUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUpdateResponse.ProtoReflect.Descriptor instead.
func (*ItemUpdateResponse) Descriptor() ([]byte, []int) {
	return file_item_update_proto_rawDescGZIP(), []int{1}
}

func (x *ItemUpdateResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_item_update_proto protoreflect.FileDescriptor

const file_item_update_proto_rawDesc = "" +
	"\n" +
	"\x11item_update.proto\x1a\n" +
	"item.proto\"Y\n" +
	"\x11ItemUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x12ItemUpdateResponse\x12\x19\n" +
	"\x04item\x18\x01 \x01(\v2\x05.ItemR\x04item2J\n" +
	"\x11ItemUpdateService\x125\n" +
	"\n" +
	"ItemUpdate\x12\x12.ItemUpdateRequest\x1a\x13.ItemUpdateResponseB\\B\x0fItemUpdateProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_item_update_proto_rawDescOnce sync.Once
	file_item_update_proto_rawDescData []byte
)

func file_item_update_proto_rawDescGZIP() []byte {
	file_item_update_proto_rawDescOnce.Do(func() {
		file_item_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_update_proto_rawDesc), len(file_item_update_proto_rawDesc)))
	})
	return file_item_update_proto_rawDescData
}

var file_item_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_update_proto_goTypes = []any{
	(*ItemUpdateRequest)(nil),  // 0: ItemUpdateRequest
	(*ItemUpdateResponse)(nil), // 1: ItemUpdateResponse
	(*Item)(nil),               // 2: Item
}
var file_item_update_proto_depIdxs = []int32{
	2, // 0: ItemUpdateResponse.item:type_name -> Item
	0, // 1: ItemUpdateService.ItemUpdate:input_type -> ItemUpdateRequest
	1, // 2: ItemUpdateService.ItemUpdate:output_type -> ItemUpdateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_update_proto_init() }
func file_item_update_proto_init() {
	if File_item_update_proto != nil {
		return
	}
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_update_proto_rawDesc), len(file_item_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_update_proto_goTypes,
		DependencyIndexes: file_item_update_proto_depIdxs,
		MessageInfos:      file_item_update_proto_msgTypes,
	}.Build()
	File_item_update_proto = out.File
	file_item_update_proto_goTypes = nil
	file_item_update_proto_depIdxs = nil
}
