// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: item_create.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCreateRequest) Reset() {
	*x = ItemCreateRequest{}
	mi := &file_item_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCreateRequest) ProtoMessage() {}

func (x *ItemCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCreateRequest.ProtoReflect.Descriptor instead.
func (*ItemCreateRequest) Descriptor() ([]byte, []int) {
	return file_item_create_proto_rawDescGZIP(), []int{0}
}

func (x *ItemCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ItemCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCreateResponse) Reset() {
	*x = ItemCreateResponse{}
	mi := &file_item_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCreateResponse) ProtoMessage() {}

func (x *ItemCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCreateResponse.ProtoReflect.Descriptor instead.
func (*ItemCreateResponse) Descriptor() ([]byte, []int) {
	return file_item_create_proto_rawDescGZIP(), []int{1}
}

func (x *ItemCreateResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_item_create_proto protoreflect.FileDescriptor

const file_item_create_proto_rawDesc = "" +
	"\n" +
	"\x11item_create.proto\x1a\n" +
	"item.proto\"I\n" +
	"\x11ItemCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"/\n" +
	"\x12ItemCreateResponse\x12\x19\n" +
	"\x04item\x18\x01 \x01(\v2\x05.ItemR\x04item2J\n" +
	"\x11ItemCreateService\x125\n" +
	"\n" +
	"ItemCreate\x12\x12.ItemCreateRequest\x1a\x13.ItemCreateResponseB\\B\x0fItemCreateProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_item_create_proto_rawDescOnce sync.Once
	file_item_create_proto_rawDescData []byte
)

func file_item_create_proto_rawDescGZIP() []byte {
	file_item_create_proto_rawDescOnce.Do(func() {
		file_item_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_create_proto_rawDesc), len(file_item_create_proto_rawDesc)))
	})
	return file_item_create_proto_rawDescData
}

var file_item_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_create_proto_goTypes = []any{
	(*ItemCreateRequest)(nil),  // 0: ItemCreateRequest
	(*ItemCreateResponse)(nil), // 1: ItemCreateResponse
	(*Item)(nil),               // 2: Item
}
var file_item_create_proto_depIdxs = []int32{
	2, // 0: ItemCreateResponse.item:type_name -> Item
	0, // 1: ItemCreateService.ItemCreate:input_type -> ItemCreateRequest
	1, // 2: ItemCreateService.ItemCreate:output_type -> ItemCreateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_create_proto_init() }
func file_item_create_proto_init() {
	if File_item_create_proto != nil {
		return
	}
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_create_proto_rawDesc), len(file_item_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_create_proto_goTypes,
		DependencyIndexes: file_item_create_proto_depIdxs,
		MessageInfos:      file_item_create_proto_msgTypes,
	}.Build()
	File_item_create_proto = out.File
	file_item_create_proto_goTypes = nil
	file_item_create_proto_depIdxs = nil
}
