// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: item_delete.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDeleteRequest) Reset() {
	*x = ItemDeleteRequest{}
	mi := &file_item_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDeleteRequest) ProtoMessage() {}

func (x *ItemDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDeleteRequest.ProtoReflect.Descriptor instead.
func (*ItemDeleteRequest) Descriptor() ([]byte, []int) {
	return file_item_delete_proto_rawDescGZIP(), []int{0}
}

func (x *ItemDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ItemDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDeleteResponse) Reset() {
	*x = ItemDeleteResponse{}
	mi := &file_item_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDeleteResponse) ProtoMessage() {}

func (x *ItemDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDeleteResponse.ProtoReflect.Descriptor instead.
func (*ItemDeleteResponse) Descriptor() ([]byte, []int) {
	return file_item_delete_proto_rawDescGZIP(), []int{1}
}

func (x *ItemDeleteResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_item_delete_proto protoreflect.FileDescriptor

const file_item_delete_proto_rawDesc = "" +
	"\n" +
	"\x11item_delete.proto\x1a\n" +
	"item.proto\"#\n" +
	"\x11ItemDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x12ItemDeleteResponse\x12\x19\n" +
	"\x04item\x18\x01 \x01(\v2\x05.ItemR\x04item2J\n" +
	"\x11ItemDeleteService\x125\n" +
	"\n" +
	"ItemDelete\x12\x12.ItemDeleteRequest\x1a\x13.ItemDeleteResponseB\\B\x0fItemDeleteProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_item_delete_proto_rawDescOnce sync.Once
	file_item_delete_proto_rawDescData []byte
)

func file_item_delete_proto_rawDescGZIP() []byte {
	file_item_delete_proto_rawDescOnce.Do(func() {
		file_item_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_delete_proto_rawDesc), len(file_item_delete_proto_rawDesc)))
	})
	return file_item_delete_proto_rawDescData
}

var file_item_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_delete_proto_goTypes = []any{
	(*ItemDeleteRequest)(nil),  // 0: ItemDeleteRequest
	(*ItemDeleteResponse)(nil), // 1: ItemDeleteResponse
	(*Item)(nil),               // 2: Item
}
var file_item_delete_proto_depIdxs = []int32{
	2, // 0: ItemDeleteResponse.item:type_name -> Item
	0, // 1: ItemDeleteService.ItemDelete:input_type -> ItemDeleteRequest
	1, // 2: ItemDeleteService.ItemDelete:output_type -> ItemDeleteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_delete_proto_init() }
func file_item_delete_proto_init() {
	if File_item_delete_proto != nil {
		return
	}
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_delete_proto_rawDesc), len(file_item_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_delete_proto_goTypes,
		DependencyIndexes: file_item_delete_proto_depIdxs,
		MessageInfos:      file_item_delete_proto_msgTypes,
	}.Build()
	File_item_delete_proto = out.File
	file_item_delete_proto_goTypes = nil
	file_item_delete_proto_depIdxs = nil
}
