// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: item_create.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemCreateService_ItemCreate_FullMethodName = "/ItemCreateService/ItemCreate"
)

// ItemCreateServiceClient is the client API for ItemCreateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemCreateService creates a new item.
type ItemCreateServiceClient interface {
	ItemCreate(ctx context.Context, in *ItemCreateRequest, opts ...grpc.CallOption) (*ItemCreateResponse, error)
}

type itemCreateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemCreateServiceClient(cc grpc.ClientConnInterface) ItemCreateServiceClient {
	return &itemCreateServiceClient{cc}
}

func (c *itemCreateServiceClient) ItemCreate(ctx context.Context, in *ItemCreateRequest, opts ...grpc.CallOption) (*ItemCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCreateResponse)
	err := c.cc.Invoke(ctx, ItemCreateService_ItemCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemCreateServiceServer is the server API for ItemCreateService service.
// All implementations must embed UnimplementedItemCreateServiceServer
// for forward compatibility.
//
// ItemCreateService creates a new item.
type ItemCreateServiceServer interface {
	ItemCreate(context.Context, *ItemCreateRequest) (*ItemCreateResponse, error)
	mustEmbedUnimplementedItemCreateServiceServer()
}

// UnimplementedItemCreateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemCreateServiceServer struct{}

func (UnimplementedItemCreateServiceServer) ItemCreate(context.Context, *ItemCreateRequest) (*ItemCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ItemCreate not implemented")
}
func (UnimplementedItemCreateServiceServer) mustEmbedUnimplementedItemCreateServiceServer() {}
func (UnimplementedItemCreateServiceServer) testEmbeddedByValue()                           {}

// UnsafeItemCreateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemCreateServiceServer will
// result in compilation errors.
type UnsafeItemCreateServiceServer interface {
	mustEmbedUnimplementedItemCreateServiceServer()
}

func RegisterItemCreateServiceServer(s grpc.ServiceRegistrar, srv ItemCreateServiceServer) {
	// If the following call panics, it indicates UnimplementedItemCreateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemCreateService_ServiceDesc, srv)
}

func _ItemCreateService_ItemCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemCreateServiceServer).ItemCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemCreateService_ItemCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemCreateServiceServer).ItemCreate(ctx, req.(*ItemCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemCreateService_ServiceDesc is the grpc.ServiceDesc for ItemCreateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemCreateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ItemCreateService",
	HandlerType: (*ItemCreateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ItemCreate",
			Handler:    _ItemCreateService_ItemCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_create.proto",
}
