// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: item_update.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemUpdateService_ItemUpdate_FullMethodName = "/ItemUpdateService/ItemUpdate"
)

// ItemUpdateServiceClient is the client API for ItemUpdateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemUpdateService updates an existing item.
type ItemUpdateServiceClient interface {
	ItemUpdate(ctx context.Context, in *ItemUpdateRequest, opts ...grpc.CallOption) (*ItemUpdateResponse, error)
}

type itemUpdateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemUpdateServiceClient(cc grpc.ClientConnInterface) ItemUpdateServiceClient {
	return &itemUpdateServiceClient{cc}
}

func (c *itemUpdateServiceClient) ItemUpdate(ctx context.Context, in *ItemUpdateRequest, opts ...grpc.CallOption) (*ItemUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemUpdateResponse)
	err := c.cc.Invoke(ctx, ItemUpdateService_ItemUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemUpdateServiceServer is the server API for ItemUpdateService service.
// All implementations must embed UnimplementedItemUpdateServiceServer
// for forward compatibility.
//
// ItemUpdateService updates an existing item.
type ItemUpdateServiceServer interface {
	ItemUpdate(context.Context, *ItemUpdateRequest) (*ItemUpdateResponse, error)
	mustEmbedUnimplementedItemUpdateServiceServer()
}

// UnimplementedItemUpdateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemUpdateServiceServer struct{}

func (UnimplementedItemUpdateServiceServer) ItemUpdate(context.Context, *ItemUpdateRequest) (*ItemUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ItemUpdate not implemented")
}
func (UnimplementedItemUpdateServiceServer) mustEmbedUnimplementedItemUpdateServiceServer() {}
func (UnimplementedItemUpdateServiceServer) testEmbeddedByValue()                           {}

// UnsafeItemUpdateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemUpdateServiceServer will
// result in compilation errors.
type UnsafeItemUpdateServiceServer interface {
	mustEmbedUnimplementedItemUpdateServiceServer()
}

func RegisterItemUpdateServiceServer(s grpc.ServiceRegistrar, srv ItemUpdateServiceServer) {
	// If the following call panics, it indicates UnimplementedItemUpdateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemUpdateService_ServiceDesc, srv)
}

func _ItemUpdateService_ItemUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemUpdateServiceServer).ItemUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemUpdateService_ItemUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemUpdateServiceServer).ItemUpdate(ctx, req.(*ItemUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemUpdateService_ServiceDesc is the grpc.ServiceDesc for ItemUpdateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemUpdateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ItemUpdateService",
	HandlerType: (*ItemUpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ItemUpdate",
			Handler:    _ItemUpdateService_ItemUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_update.proto",
}
