// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: item_list.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListRequest) Reset() {
	*x = ItemListRequest{}
	mi := &file_item_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListRequest) ProtoMessage() {}

func (x *ItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListRequest.ProtoReflect.Descriptor instead.
func (*ItemListRequest) Descriptor() ([]byte, []int) {
	return file_item_list_proto_rawDescGZIP(), []int{0}
}

func (x *ItemListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ItemListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListResponse) Reset() {
	*x = ItemListResponse{}
	mi := &file_item_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListResponse) ProtoMessage() {}

func (x *ItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListResponse.ProtoReflect.Descriptor instead.
func (*ItemListResponse) Descriptor() ([]byte, []int) {
	return file_item_list_proto_rawDescGZIP(), []int{1}
}

func (x *ItemListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_item_list_proto protoreflect.FileDescriptor

const file_item_list_proto_rawDesc = "" +
	"\n" +
	"\x0fitem_list.proto\x1a\n" +
	"item.proto\"?\n" +
	"\x0fItemListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"/\n" +
	"\x10ItemListResponse\x12\x1b\n" +
	"\x05items\x18\x01 \x03(\v2\x05.ItemR\x05items2B\n" +
	"\x0fItemListService\x12/\n" +
	"\bItemList\x12\x10.ItemListRequest\x1a\x11.ItemListResponseBZB\rItemListProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_item_list_proto_rawDescOnce sync.Once
	file_item_list_proto_rawDescData []byte
)

func file_item_list_proto_rawDescGZIP() []byte {
	file_item_list_proto_rawDescOnce.Do(func() {
		file_item_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_list_proto_rawDesc), len(file_item_list_proto_rawDesc)))
	})
	return file_item_list_proto_rawDescData
}

var file_item_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_list_proto_goTypes = []any{
	(*ItemListRequest)(nil),  // 0: ItemListRequest
	(*ItemListResponse)(nil), // 1: ItemListResponse
	(*Item)(nil),             // 2: Item
}
var file_item_list_proto_depIdxs = []int32{
	2, // 0: ItemListResponse.items:type_name -> Item
	0, // 1: ItemListService.ItemList:input_type -> ItemListRequest
	1, // 2: ItemListService.ItemList:output_type -> ItemListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_list_proto_init() }
func file_item_list_proto_init() {
	if File_item_list_proto != nil {
		return
	}
	file_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_list_proto_rawDesc), len(file_item_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_list_proto_goTypes,
		DependencyIndexes: file_item_list_proto_depIdxs,
		MessageInfos:      file_item_list_proto_msgTypes,
	}.Build()
	File_item_list_proto = out.File
	file_item_list_proto_goTypes = nil
	file_item_list_proto_depIdxs = nil
}
