// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: item_delete.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemDeleteService_ItemDelete_FullMethodName = "/ItemDeleteService/ItemDelete"
)

// ItemDeleteServiceClient is the client API for ItemDeleteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemDeleteService deletes an item by ID.
type ItemDeleteServiceClient interface {
	ItemDelete(ctx context.Context, in *ItemDeleteRequest, opts ...grpc.CallOption) (*ItemDeleteResponse, error)
}

type itemDeleteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemDeleteServiceClient(cc grpc.ClientConnInterface) ItemDeleteServiceClient {
	return &itemDeleteServiceClient{cc}
}

func (c *itemDeleteServiceClient) ItemDelete(ctx context.Context, in *ItemDeleteRequest, opts ...grpc.CallOption) (*ItemDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemDeleteResponse)
	err := c.cc.Invoke(ctx, ItemDeleteService_ItemDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemDeleteServiceServer is the server API for ItemDeleteService service.
// All implementations must embed UnimplementedItemDeleteServiceServer
// for forward compatibility.
//
// ItemDeleteService deletes an item by ID.
type ItemDeleteServiceServer interface {
	ItemDelete(context.Context, *ItemDeleteRequest) (*ItemDeleteResponse, error)
	mustEmbedUnimplementedItemDeleteServiceServer()
}

// UnimplementedItemDeleteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemDeleteServiceServer struct{}

func (UnimplementedItemDeleteServiceServer) ItemDelete(context.Context, *ItemDeleteRequest) (*ItemDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ItemDelete not implemented")
}
func (UnimplementedItemDeleteServiceServer) mustEmbedUnimplementedItemDeleteServiceServer() {}
func (UnimplementedItemDeleteServiceServer) testEmbeddedByValue()                           {}

// UnsafeItemDeleteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemDeleteServiceServer will
// result in compilation errors.
type UnsafeItemDeleteServiceServer interface {
	mustEmbedUnimplementedItemDeleteServiceServer()
}

func RegisterItemDeleteServiceServer(s grpc.ServiceRegistrar, srv ItemDeleteServiceServer) {
	// If the following call panics, it indicates UnimplementedItemDeleteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemDeleteService_ServiceDesc, srv)
}

func _ItemDeleteService_ItemDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemDeleteServiceServer).ItemDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemDeleteService_ItemDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemDeleteServiceServer).ItemDelete(ctx, req.(*ItemDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemDeleteService_ServiceDesc is the grpc.ServiceDesc for ItemDeleteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemDeleteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ItemDeleteService",
	HandlerType: (*ItemDeleteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ItemDelete",
			Handler:    _ItemDeleteService_ItemDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_delete.proto",
}
