// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: status.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DependencyStatus int32

const (
	// DEPENDENCY_STATUS_UNSPECIFIED means the application has failed to, or has not yet
	// assess the status of the given dependency.
	DependencyStatus_DEPENDENCY_STATUS_UNSPECIFIED DependencyStatus = 0
	// DEPENDENCY_STATUS_UP means the dependency was successfully pinged, and
	// should serve normally.
	DependencyStatus_DEPENDENCY_STATUS_UP DependencyStatus = 1
	// DEPENDENCY_STATUS_DOWN means the application has contacted the dependency, but it
	// failed to respond with a proper status.
	DependencyStatus_DEPENDENCY_STATUS_DOWN DependencyStatus = 2
)

// Enum value maps for DependencyStatus.
var (
	DependencyStatus_name = map[int32]string{
		0: "DEPENDENCY_STATUS_UNSPECIFIED",
		1: "DEPENDENCY_STATUS_UP",
		2: "DEPENDENCY_STATUS_DOWN",
	}
	DependencyStatus_value = map[string]int32{
		"DEPENDENCY_STATUS_UNSPECIFIED": 0,
		"DEPENDENCY_STATUS_UP":          1,
		"DEPENDENCY_STATUS_DOWN":        2,
	}
)

func (x DependencyStatus) Enum() *DependencyStatus {
	p := new(DependencyStatus)
	*p = x
	return p
}

func (x DependencyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_status_proto_enumTypes[0].Descriptor()
}

func (DependencyStatus) Type() protoreflect.EnumType {
	return &file_status_proto_enumTypes[0]
}

func (x DependencyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyStatus.Descriptor instead.
func (DependencyStatus) EnumDescriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

type DependencyHealth struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status DependencyStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=DependencyStatus" json:"status,omitempty"`
	// The error that occurred when checking for the dependency status, if any.
	Err           string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyHealth) Reset() {
	*x = DependencyHealth{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyHealth) ProtoMessage() {}

func (x *DependencyHealth) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyHealth.ProtoReflect.Descriptor instead.
func (*DependencyHealth) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *DependencyHealth) GetStatus() DependencyStatus {
	if x != nil {
		return x.Status
	}
	return DependencyStatus_DEPENDENCY_STATUS_UNSPECIFIED
}

func (x *DependencyHealth) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{1}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      *DependencyHealth      `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetPostgres() *DependencyHealth {
	if x != nil {
		return x.Postgres
	}
	return nil
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\"O\n" +
	"\x10DependencyHealth\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.DependencyStatusR\x06status\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"\x0f\n" +
	"\rStatusRequest\"?\n" +
	"\x0eStatusResponse\x12-\n" +
	"\bpostgres\x18\x01 \x01(\v2\x11.DependencyHealthR\bpostgres*k\n" +
	"\x10DependencyStatus\x12!\n" +
	"\x1dDEPENDENCY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEPENDENCY_STATUS_UP\x10\x01\x12\x1a\n" +
	"\x16DEPENDENCY_STATUS_DOWN\x10\x022:\n" +
	"\rStatusService\x12)\n" +
	"\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponseBXB\vStatusProtoP\x01ZGgithub.com/a-novel/service-template/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_status_proto_goTypes = []any{
	(DependencyStatus)(0),    // 0: DependencyStatus
	(*DependencyHealth)(nil), // 1: DependencyHealth
	(*StatusRequest)(nil),    // 2: StatusRequest
	(*StatusResponse)(nil),   // 3: StatusResponse
}
var file_status_proto_depIdxs = []int32{
	0, // 0: DependencyHealth.status:type_name -> DependencyStatus
	1, // 1: StatusResponse.postgres:type_name -> DependencyHealth
	2, // 2: StatusService.Status:input_type -> StatusRequest
	3, // 3: StatusService.Status:output_type -> StatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		EnumInfos:         file_status_proto_enumTypes,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
