// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"

	"github.com/a-novel/service-template/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreateRepository creates a new instance of MockItemCreateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateRepository {
	mock := &MockItemCreateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateRepository is an autogenerated mock type for the ItemCreateRepository type
type MockItemCreateRepository struct {
	mock.Mock
}

type MockItemCreateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateRepository) EXPECT() *MockItemCreateRepository_Expecter {
	return &MockItemCreateRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateRepository
func (_mock *MockItemCreateRepository) Exec(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemCreateRequest
func (_e *MockItemCreateRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockItemCreateRepository_Exec_Call {
	return &MockItemCreateRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemCreateRequest)) *MockItemCreateRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateRepository_Exec_Call) Return(item *dao.Item, err error) *MockItemCreateRepository_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreateRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error)) *MockItemCreateRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteRepository creates a new instance of MockItemDeleteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteRepository {
	mock := &MockItemDeleteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteRepository is an autogenerated mock type for the ItemDeleteRepository type
type MockItemDeleteRepository struct {
	mock.Mock
}

type MockItemDeleteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteRepository) EXPECT() *MockItemDeleteRepository_Expecter {
	return &MockItemDeleteRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteRepository
func (_mock *MockItemDeleteRepository) Exec(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemDeleteRequest
func (_e *MockItemDeleteRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockItemDeleteRepository_Exec_Call {
	return &MockItemDeleteRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemDeleteRequest)) *MockItemDeleteRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteRepository_Exec_Call) Return(item *dao.Item, err error) *MockItemDeleteRepository_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeleteRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error)) *MockItemDeleteRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetRepository creates a new instance of MockItemGetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetRepository {
	mock := &MockItemGetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetRepository is an autogenerated mock type for the ItemGetRepository type
type MockItemGetRepository struct {
	mock.Mock
}

type MockItemGetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetRepository) EXPECT() *MockItemGetRepository_Expecter {
	return &MockItemGetRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetRepository
func (_mock *MockItemGetRepository) Exec(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemGetRequest
func (_e *MockItemGetRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockItemGetRepository_Exec_Call {
	return &MockItemGetRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemGetRequest)) *MockItemGetRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetRepository_Exec_Call) Return(item *dao.Item, err error) *MockItemGetRepository_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error)) *MockItemGetRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListRepository creates a new instance of MockItemListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListRepository {
	mock := &MockItemListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListRepository is an autogenerated mock type for the ItemListRepository type
type MockItemListRepository struct {
	mock.Mock
}

type MockItemListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListRepository) EXPECT() *MockItemListRepository_Expecter {
	return &MockItemListRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListRepository
func (_mock *MockItemListRepository) Exec(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) ([]*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) []*dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemListRequest
func (_e *MockItemListRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockItemListRepository_Exec_Call {
	return &MockItemListRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemListRequest)) *MockItemListRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListRepository_Exec_Call) Return(items []*dao.Item, err error) *MockItemListRepository_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error)) *MockItemListRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateRepository creates a new instance of MockItemUpdateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateRepository {
	mock := &MockItemUpdateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateRepository is an autogenerated mock type for the ItemUpdateRepository type
type MockItemUpdateRepository struct {
	mock.Mock
}

type MockItemUpdateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateRepository) EXPECT() *MockItemUpdateRepository_Expecter {
	return &MockItemUpdateRepository_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateRepository
func (_mock *MockItemUpdateRepository) Exec(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateRepository_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateRepository_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemUpdateRequest
func (_e *MockItemUpdateRepository_Expecter) Exec(ctx interface{}, request interface{}) *MockItemUpdateRepository_Exec_Call {
	return &MockItemUpdateRepository_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateRepository_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemUpdateRequest)) *MockItemUpdateRepository_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateRepository_Exec_Call) Return(item *dao.Item, err error) *MockItemUpdateRepository_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdateRepository_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error)) *MockItemUpdateRepository_Exec_Call {
	_c.Call.Return(run)
	return _c
}
