// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-template/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreateService creates a new instance of MockItemCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateService {
	mock := &MockItemCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateService is an autogenerated mock type for the ItemCreateService type
type MockItemCreateService struct {
	mock.Mock
}

type MockItemCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateService) EXPECT() *MockItemCreateService_Expecter {
	return &MockItemCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateService
func (_mock *MockItemCreateService) Exec(ctx context.Context, request *services.ItemCreateRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemCreateRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemCreateRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemCreateRequest
func (_e *MockItemCreateService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemCreateService_Exec_Call {
	return &MockItemCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemCreateRequest)) *MockItemCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateService_Exec_Call) Return(v *services.Item, err error) *MockItemCreateService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemCreateRequest) (*services.Item, error)) *MockItemCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteService creates a new instance of MockItemDeleteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteService {
	mock := &MockItemDeleteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteService is an autogenerated mock type for the ItemDeleteService type
type MockItemDeleteService struct {
	mock.Mock
}

type MockItemDeleteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteService) EXPECT() *MockItemDeleteService_Expecter {
	return &MockItemDeleteService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteService
func (_mock *MockItemDeleteService) Exec(ctx context.Context, request *services.ItemDeleteRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemDeleteRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemDeleteRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemDeleteRequest
func (_e *MockItemDeleteService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemDeleteService_Exec_Call {
	return &MockItemDeleteService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemDeleteRequest)) *MockItemDeleteService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteService_Exec_Call) Return(v *services.Item, err error) *MockItemDeleteService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemDeleteService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemDeleteRequest) (*services.Item, error)) *MockItemDeleteService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetService creates a new instance of MockItemGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetService {
	mock := &MockItemGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetService is an autogenerated mock type for the ItemGetService type
type MockItemGetService struct {
	mock.Mock
}

type MockItemGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetService) EXPECT() *MockItemGetService_Expecter {
	return &MockItemGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetService
func (_mock *MockItemGetService) Exec(ctx context.Context, request *services.ItemGetRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemGetRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemGetRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemGetRequest
func (_e *MockItemGetService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemGetService_Exec_Call {
	return &MockItemGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemGetRequest)) *MockItemGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetService_Exec_Call) Return(v *services.Item, err error) *MockItemGetService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemGetRequest) (*services.Item, error)) *MockItemGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListService creates a new instance of MockItemListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListService {
	mock := &MockItemListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListService is an autogenerated mock type for the ItemListService type
type MockItemListService struct {
	mock.Mock
}

type MockItemListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListService) EXPECT() *MockItemListService_Expecter {
	return &MockItemListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListService
func (_mock *MockItemListService) Exec(ctx context.Context, request *services.ItemListRequest) ([]*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemListRequest) ([]*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemListRequest) []*services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemListRequest
func (_e *MockItemListService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemListService_Exec_Call {
	return &MockItemListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemListRequest)) *MockItemListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListService_Exec_Call) Return(vs []*services.Item, err error) *MockItemListService_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockItemListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemListRequest) ([]*services.Item, error)) *MockItemListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateService creates a new instance of MockItemUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateService {
	mock := &MockItemUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateService is an autogenerated mock type for the ItemUpdateService type
type MockItemUpdateService struct {
	mock.Mock
}

type MockItemUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateService) EXPECT() *MockItemUpdateService_Expecter {
	return &MockItemUpdateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateService
func (_mock *MockItemUpdateService) Exec(ctx context.Context, request *services.ItemUpdateRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemUpdateRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemUpdateRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemUpdateRequest
func (_e *MockItemUpdateService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemUpdateService_Exec_Call {
	return &MockItemUpdateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemUpdateRequest)) *MockItemUpdateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateService_Exec_Call) Return(v *services.Item, err error) *MockItemUpdateService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemUpdateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemUpdateRequest) (*services.Item, error)) *MockItemUpdateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemCreatePublicService creates a new instance of MockItemCreatePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreatePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreatePublicService {
	mock := &MockItemCreatePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreatePublicService is an autogenerated mock type for the ItemCreatePublicService type
type MockItemCreatePublicService struct {
	mock.Mock
}

type MockItemCreatePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreatePublicService) EXPECT() *MockItemCreatePublicService_Expecter {
	return &MockItemCreatePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreatePublicService
func (_mock *MockItemCreatePublicService) Exec(ctx context.Context, request *services.ItemCreateRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemCreateRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemCreateRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreatePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreatePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemCreateRequest
func (_e *MockItemCreatePublicService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemCreatePublicService_Exec_Call {
	return &MockItemCreatePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreatePublicService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemCreateRequest)) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreatePublicService_Exec_Call) Return(v *services.Item, err error) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemCreatePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemCreateRequest) (*services.Item, error)) *MockItemCreatePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeletePublicService creates a new instance of MockItemDeletePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeletePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeletePublicService {
	mock := &MockItemDeletePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeletePublicService is an autogenerated mock type for the ItemDeletePublicService type
type MockItemDeletePublicService struct {
	mock.Mock
}

type MockItemDeletePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeletePublicService) EXPECT() *MockItemDeletePublicService_Expecter {
	return &MockItemDeletePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeletePublicService
func (_mock *MockItemDeletePublicService) Exec(ctx context.Context, request *services.ItemDeleteRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemDeleteRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemDeleteRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeletePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeletePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemDeleteRequest
func (_e *MockItemDeletePublicService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemDeletePublicService_Exec_Call {
	return &MockItemDeletePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeletePublicService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemDeleteRequest)) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeletePublicService_Exec_Call) Return(v *services.Item, err error) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemDeletePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemDeleteRequest) (*services.Item, error)) *MockItemDeletePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetPublicService creates a new instance of MockItemGetPublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetPublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetPublicService {
	mock := &MockItemGetPublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetPublicService is an autogenerated mock type for the ItemGetPublicService type
type MockItemGetPublicService struct {
	mock.Mock
}

type MockItemGetPublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetPublicService) EXPECT() *MockItemGetPublicService_Expecter {
	return &MockItemGetPublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetPublicService
func (_mock *MockItemGetPublicService) Exec(ctx context.Context, request *services.ItemGetRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemGetRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemGetRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetPublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetPublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemGetRequest
func (_e *MockItemGetPublicService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemGetPublicService_Exec_Call {
	return &MockItemGetPublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetPublicService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemGetRequest)) *MockItemGetPublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetPublicService_Exec_Call) Return(v *services.Item, err error) *MockItemGetPublicService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemGetPublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemGetRequest) (*services.Item, error)) *MockItemGetPublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListPublicService creates a new instance of MockItemListPublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListPublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListPublicService {
	mock := &MockItemListPublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListPublicService is an autogenerated mock type for the ItemListPublicService type
type MockItemListPublicService struct {
	mock.Mock
}

type MockItemListPublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListPublicService) EXPECT() *MockItemListPublicService_Expecter {
	return &MockItemListPublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListPublicService
func (_mock *MockItemListPublicService) Exec(ctx context.Context, request *services.ItemListRequest) ([]*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemListRequest) ([]*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemListRequest) []*services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListPublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListPublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemListRequest
func (_e *MockItemListPublicService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemListPublicService_Exec_Call {
	return &MockItemListPublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListPublicService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemListRequest)) *MockItemListPublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListPublicService_Exec_Call) Return(vs []*services.Item, err error) *MockItemListPublicService_Exec_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockItemListPublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemListRequest) ([]*services.Item, error)) *MockItemListPublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdatePublicService creates a new instance of MockItemUpdatePublicService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdatePublicService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdatePublicService {
	mock := &MockItemUpdatePublicService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdatePublicService is an autogenerated mock type for the ItemUpdatePublicService type
type MockItemUpdatePublicService struct {
	mock.Mock
}

type MockItemUpdatePublicService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdatePublicService) EXPECT() *MockItemUpdatePublicService_Expecter {
	return &MockItemUpdatePublicService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdatePublicService
func (_mock *MockItemUpdatePublicService) Exec(ctx context.Context, request *services.ItemUpdateRequest) (*services.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemUpdateRequest) (*services.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.ItemUpdateRequest) *services.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdatePublicService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdatePublicService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *services.ItemUpdateRequest
func (_e *MockItemUpdatePublicService_Expecter) Exec(ctx interface{}, request interface{}) *MockItemUpdatePublicService_Exec_Call {
	return &MockItemUpdatePublicService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdatePublicService_Exec_Call) Run(run func(ctx context.Context, request *services.ItemUpdateRequest)) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*services.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdatePublicService_Exec_Call) Return(v *services.Item, err error) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockItemUpdatePublicService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *services.ItemUpdateRequest) (*services.Item, error)) *MockItemUpdatePublicService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
