name: auto-assign author
on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: a-novel-kit/workflows/generic-actions/assign-bot@v1.19.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
