name: main

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  generated-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: go generate
        shell: bash
        run: go generate ./...
      - uses: a-novel-kit/workflows/generic-actions/check-changes@master
        with:
          fail_message: go generate definitions are not up-to-date, please run 'go generate ./...' and commit the changes

  lint-go:
    runs-on: ubuntu-latest
    needs: [generated-go]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/lint-go@master

  lint-proto:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: bufbuild/buf-action@v1

  lint-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/lint-node@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          app_id: ${{ vars.DEPENDENCY_BOT_ID }}

  test:
    needs: [lint-go, build-database]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.test.outputs.artifact-id }}
    services:
      postgres:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-migrations
      - uses: a-novel-kit/workflows/go-actions/test-go@master
        id: test
        with:
          filter_extra_patterns: "| grep /internal | grep -v /protogen"
          skip_setup: true
          test_artifact: gotest
          coverage_artifact: gocover
          coverage_file: coverage.txt
          modfile: gotestsum.mod

  test-pkg:
    needs: [build-database, build-standalone-grpc]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.test.outputs.artifact-id }}
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      service-template:
        image: ghcr.io/a-novel/service-template/standalone-grpc@${{ needs.build-standalone-grpc.outputs.digest }}
        ports:
          - "8080:8080"
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          POSTGRES_DSN: postgres://postgres:postgres@postgres-template:5432/postgres?sslmode=disable
    env:
      GRPC_URL: "localhost:8080"
    steps:
      - uses: actions/checkout@v6
      - uses: a-novel-kit/workflows/go-actions/test-go@master
        id: test
        with:
          filter_extra_patterns: "| grep /pkg"
          skip_setup: true
          test_artifact: gotestpkg
          coverage_artifact: gocoverpkg
          coverage_file: coverage_pkg.txt
          modfile: gotestsum.mod

  test-pkg-js:
    runs-on: ubuntu-latest
    needs: [build-database, build-standalone-rest]
    permissions:
      contents: read
      packages: read
    outputs:
      artifact-id: ${{ steps.test.outputs.artifact-id }}
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      service-template:
        image: ghcr.io/a-novel/service-template/standalone-rest@${{ needs.build-standalone-rest.outputs.digest }}
        ports:
          - "8080:8080"
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          POSTGRES_DSN: postgres://postgres:postgres@postgres-template:5432/postgres?sslmode=disable
    env:
      REST_URL: "http://localhost:8080"
    steps:
      - uses: a-novel-kit/workflows/node-actions/test-node@master
        id: test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          app_id: ${{ vars.DEPENDENCY_BOT_ID }}
          coverage_artifact: jscover

  build-database:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    steps:
      - uses: a-novel-kit/workflows/build-actions/docker@master
        id: build
        with:
          file: builds/database.Dockerfile
          image_name: ${{ github.repository }}/database
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: >-
            -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" 
            -e POSTGRES_USER="${POSTGRES_USER}" 
            -e POSTGRES_DB="${POSTGRES_DB}"
            -e POSTGRES_HOST_AUTH_METHOD="${POSTGRES_HOST_AUTH_METHOD}"
            -e POSTGRES_INITDB_ARGS="${POSTGRES_INITDB_ARGS}"

  build-migrations:
    runs-on: ubuntu-latest
    needs: [build-database]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: a-novel-kit/workflows/build-actions/docker-job@master
        with:
          file: builds/migrations.Dockerfile
          image_name: ${{ github.repository }}/jobs/migrations
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e POSTGRES_DSN="${POSTGRES_DSN}"

  build-grpc:
    needs: [test, build-database]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-migrations
      - uses: a-novel-kit/workflows/build-actions/docker@master
        with:
          file: builds/grpc.Dockerfile
          image_name: ${{ github.repository }}/grpc
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e POSTGRES_DSN="${POSTGRES_DSN}"

  build-standalone-grpc:
    needs: [test, build-database]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-migrations
      - uses: a-novel-kit/workflows/build-actions/docker@master
        id: build
        with:
          file: builds/standalone.grpc.Dockerfile
          image_name: ${{ github.repository }}/standalone-grpc
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e POSTGRES_DSN="${POSTGRES_DSN}"

  build-rest:
    needs: [test, build-database]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-migrations
      - uses: a-novel-kit/workflows/build-actions/docker@master
        with:
          file: builds/rest.Dockerfile
          image_name: ${{ github.repository }}/rest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e POSTGRES_DSN="${POSTGRES_DSN}"

  build-standalone-rest:
    needs: [test, build-database]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    services:
      postgres-template:
        image: ghcr.io/a-novel/service-template/database@${{ needs.build-database.outputs.digest }}
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-migrations
      - uses: a-novel-kit/workflows/build-actions/docker@master
        id: build
        with:
          file: builds/standalone.rest.Dockerfile
          image_name: ${{ github.repository }}/standalone-rest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_args: -e POSTGRES_DSN="${POSTGRES_DSN}"

  build-js:
    needs: [test-pkg-js]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/build-node@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          app_id: ${{ vars.DEPENDENCY_BOT_ID }}
          build_action: "build:rest"

  report-grc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [test, test-pkg]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/go-actions/go-report-card@master
        if: github.ref == 'refs/heads/master' && success()

  report-codecov:
    runs-on: ubuntu-latest
    needs: [test, test-pkg, test-pkg-js]
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/codecov@master
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          coverage_files: coverage.txt,coverage_pkg.txt,coverage/*
          coverage_artifact_ids: ${{ needs.test.outputs.artifact-id }},${{ needs.test-pkg.outputs.artifact-id }},${{ needs.test-pkg-js.outputs.artifact-id }}

  publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    needs: [build-js]
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: |
          mkdir _site
          mv openapi.html _site/index.html
          mv openapi.yaml _site/openapi.yaml
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
      - id: deployment
        uses: actions/deploy-pages@v4
